idf_component_register(
    SRCS
        "main.c"
        "app_settings.c"
        "stepper.c"
        "wifi_manager.c"
        "homekit_service.c"
        "webui.c"
        "led_indicator.c"
    INCLUDE_DIRS "."
    REQUIRES
        nvs_flash
        esp_wifi
        esp_netif
        esp_event
        esp_http_server
        esp_timer
        esp_hw_support
        mdns
        driver
        esp_hap_core
        esp_hap_apple_profiles
        led_strip
)
