#pragma once

/* The whole control panel as a single string. Designed to be self-contained:
 * no external CSS/JS/font resources, so it works whether or not the device
 * (or your phone) has internet. */

static const char WEBUI_HTML[] =
"<!doctype html>"
"<html lang=en>"
"<meta charset=utf-8>"
"<meta name=viewport content='width=device-width,initial-scale=1'>"
"<title>AIRCOVER // CONTROL</title>"

"<style>"
":root{"
"--bg:#0a0a0a;--panel:#111;--ink:#e8b860;--dim:#6b5530;"
"--rule:#2a2a2a;--warn:#ff6b35;--danger:#d33;--ok:#7fb069;"
"}"
"*{box-sizing:border-box;margin:0;padding:0}"
"html,body{background:var(--bg);color:var(--ink);"
"font-family:ui-monospace,'SF Mono','JetBrains Mono',Menlo,Consolas,monospace;"
"font-size:13px;line-height:1.5;min-height:100vh}"
"body{padding:18px;max-width:760px;margin:0 auto;"
"background-image:repeating-linear-gradient(0deg,rgba(232,184,96,0.015) 0px,rgba(232,184,96,0.015) 1px,transparent 1px,transparent 3px)}"

"header{display:flex;justify-content:space-between;align-items:baseline;"
"border-bottom:1px solid var(--ink);padding-bottom:10px;margin-bottom:18px}"
"h1{font-size:14px;letter-spacing:.45em;font-weight:600}"
"h1 span{color:var(--dim)}"
".sig{font-size:10px;letter-spacing:.25em;color:var(--dim)}"
".sig b{color:var(--ok)}"
".sig b.bad{color:var(--warn)}"

".panel{border:1px solid var(--rule);background:var(--panel);"
"padding:14px;margin-bottom:14px;position:relative}"
".panel::before{content:attr(data-tag);position:absolute;top:-7px;left:12px;"
"background:var(--bg);padding:0 8px;font-size:10px;letter-spacing:.3em;color:var(--dim)}"

".readout{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:6px}"
".readout .cell{border:1px solid var(--rule);padding:8px}"
".readout .k{font-size:9px;letter-spacing:.25em;color:var(--dim);margin-bottom:4px}"
".readout .v{font-size:22px;font-weight:700;letter-spacing:.05em}"
".readout .u{font-size:10px;color:var(--dim);margin-left:3px}"
".state-MOVING{color:var(--warn)}"
".state-STOPPED{color:var(--ok)}"

".slider-wrap{margin:14px 0 6px;position:relative}"
".slider-track{height:30px;background:#000;border:1px solid var(--rule);position:relative;overflow:hidden}"
".slider-fill{position:absolute;top:0;left:0;height:100%;background:var(--ink);opacity:.25}"
".slider-target{position:absolute;top:0;height:100%;width:2px;background:var(--warn)}"
"input[type=range]{width:100%;-webkit-appearance:none;background:transparent;margin-top:-30px;position:relative;z-index:2;height:30px}"
"input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:8px;height:30px;background:var(--ink);border:0;cursor:pointer}"
"input[type=range]::-moz-range-thumb{width:8px;height:30px;background:var(--ink);border:0;cursor:pointer}"
".ticks{display:flex;justify-content:space-between;font-size:9px;color:var(--dim);letter-spacing:.2em;margin-top:6px}"

".row{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}"
".row.eq>*{flex:1}"
"button,.btn{background:#000;color:var(--ink);border:1px solid var(--ink);"
"padding:9px 12px;font-family:inherit;font-size:12px;letter-spacing:.15em;cursor:pointer;"
"transition:background .1s,color .1s}"
"button:hover,.btn:hover{background:var(--ink);color:#000}"
"button:active{transform:translateY(1px)}"
"button.danger{border-color:var(--danger);color:var(--danger)}"
"button.danger:hover{background:var(--danger);color:#000}"
"button.warn{border-color:var(--warn);color:var(--warn)}"
"button.warn:hover{background:var(--warn);color:#000}"
"button:disabled{opacity:.35;cursor:not-allowed}"
"button:disabled:hover{background:#000;color:var(--ink)}"

".kv{display:grid;grid-template-columns:1fr auto;gap:8px 14px;align-items:center;margin-top:8px}"
".kv label{font-size:11px;letter-spacing:.15em;color:var(--dim)}"
".kv input[type=number],.kv input[type=text]{background:#000;border:1px solid var(--rule);"
"color:var(--ink);padding:6px 8px;font-family:inherit;font-size:12px;width:120px;text-align:right}"
".kv input:focus{outline:0;border-color:var(--ink)}"
".kv .chk{display:flex;gap:6px;align-items:center;justify-content:flex-end}"
".kv input[type=checkbox]{appearance:none;width:14px;height:14px;border:1px solid var(--ink);background:#000;cursor:pointer;position:relative}"
".kv input[type=checkbox]:checked::after{content:'';position:absolute;top:2px;left:2px;right:2px;bottom:2px;background:var(--ink)}"

"#log{background:#000;border:1px solid var(--rule);padding:10px;height:200px;overflow:auto;"
"font-size:11px;line-height:1.4;white-space:pre-wrap;word-break:break-word}"
"#log .E{color:#ff5454}"
"#log .W{color:var(--warn)}"
"#log .I{color:var(--ink)}"
"#log .D{color:var(--dim)}"
"#log .V{color:#888}"

".hint{font-size:10px;color:var(--dim);margin-top:6px;letter-spacing:.05em}"
".flash{transition:background .3s;background:rgba(232,184,96,.15)}"
"</style>"

"<body>"
"<header>"
"  <h1>AIRCOVER <span>// CONTROL</span></h1>"
"  <div class=sig>SYS <b id=sigSys>OK</b> &middot; HK <b id=sigHK>?</b></div>"
"</header>"

"<section class=panel data-tag='STATUS'>"
"  <div class=readout>"
"    <div class=cell><div class=k>POS</div><div class=v><span id=rPos>0</span><span class=u>%</span></div></div>"
"    <div class=cell><div class=k>TARGET</div><div class=v><span id=rTgt>0</span><span class=u>%</span></div></div>"
"    <div class=cell><div class=k>STEPS</div><div class=v id=rSteps>0</div></div>"
"    <div class=cell><div class=k>STATE</div><div class=v id=rState>--</div></div>"
"  </div>"

"  <div class=slider-wrap>"
"    <div class=slider-track><div class=slider-fill id=fill></div><div class=slider-target id=tmark></div></div>"
"    <input type=range id=slider min=0 max=100 value=0 step=1>"
"  </div>"
"  <div class=ticks><span>0</span><span>25</span><span>50</span><span>75</span><span>100</span></div>"

"  <div class='row eq' style='margin-top:14px'>"
"    <button onclick=\"move(0)\">FULL CLOSE</button>"
"    <button onclick=\"move(50)\">HALF</button>"
"    <button onclick=\"move(100)\">FULL OPEN</button>"
"    <button class=warn onclick=\"api('/api/stop',{})\">STOP</button>"
"  </div>"
"</section>"

"<section class=panel data-tag='JOG / CALIBRATION'>"
"  <div class='row eq'>"
"    <button onclick=\"jog(-500)\">&#9664;&#9664; -500</button>"
"    <button onclick=\"jog(-100)\">&#9664; -100</button>"
"    <button onclick=\"jog(-10)\">-10</button>"
"    <button onclick=\"jog(10)\">+10</button>"
"    <button onclick=\"jog(100)\">+100 &#9654;</button>"
"    <button onclick=\"jog(500)\">+500 &#9654;&#9654;</button>"
"  </div>"
"  <div class=row style='margin-top:14px'>"
"    <input type=number id=jogN placeholder='custom steps' style='background:#000;border:1px solid var(--rule);color:var(--ink);padding:8px;font-family:inherit;width:140px'>"
"    <button onclick=\"jog(parseInt(document.getElementById('jogN').value)||0)\">JOG</button>"
"  </div>"
"  <div class=hint>"
"    Calibration flow: jog to the fully-CLOSED position, then SET ZERO. "
"    Jog up to the fully-OPEN position, then SET OPEN. The current step count "
"    becomes the new 100% reference."
"  </div>"
"  <div class='row eq' style='margin-top:10px'>"
"    <button onclick=\"calibrate('set_zero')\">SET ZERO HERE</button>"
"    <button onclick=\"calibrate('set_open')\">SET OPEN HERE</button>"
"  </div>"
"</section>"

"<section class=panel data-tag='CONFIG'>"
"  <div class=kv>"
"    <label>STEP PERIOD (us)</label>"
"    <input type=number id=cfgPeriod min=900 max=20000 step=100>"
"    <label>HOLD WHEN IDLE</label>"
"    <div class=chk><input type=checkbox id=cfgHold></div>"
"    <label>FULL-OPEN STEPS</label>"
"    <input type=number id=cfgFullOpen min=100 step=1>"
"    <label>HOMEKIT NAME</label>"
"    <input type=text id=cfgName maxlength=32>"
"    <label>HOMEKIT SETUP CODE</label>"
"    <input type=text id=cfgCode maxlength=10 placeholder='XXX-XX-XXX'>"
"  </div>"
"  <div class='row eq' style='margin-top:14px'>"
"    <button onclick=saveConfig()>APPLY &amp; SAVE</button>"
"  </div>"
"  <div class=hint>Changing the HomeKit name/code requires re-pairing in the Home app.</div>"
"</section>"

"<section class=panel data-tag='LOG'>"
"  <div id=log></div>"
"  <div class='row eq' style='margin-top:8px'>"
"    <button onclick=\"document.getElementById('log').innerHTML=''\">CLEAR</button>"
"    <button onclick=toggleAutoscroll() id=autoBtn>AUTOSCROLL: ON</button>"
"  </div>"
"</section>"

"<section class=panel data-tag='DANGER'>"
"  <div class=hint>"
"    Factory reset clears all settings: WiFi credentials, HomeKit pairings, "
"    calibration, and step count. The device will reboot into SoftAP setup mode."
"  </div>"
"  <div class='row eq' style='margin-top:10px'>"
"    <button class=danger onclick=resetAll()>FACTORY RESET</button>"
"    <button class=warn onclick=\"api('/api/reboot',{})\">REBOOT</button>"
"  </div>"
"</section>"

"<script>"
"let autoscroll=true,userDragging=false,lastTarget=0;"
"const $=id=>document.getElementById(id);"

"async function api(path,body){"
"  const opts={method:'POST',headers:{'Content-Type':'application/json'}};"
"  if(body!==undefined) opts.body=JSON.stringify(body);"
"  try{"
"    const r=await fetch(path,opts);"
"    if(!r.ok) throw new Error(r.status+' '+r.statusText);"
"    return r.headers.get('content-type')?.includes('json')?await r.json():await r.text();"
"  }catch(e){console.error(path,e);return null;}"
"}"

"async function refresh(){"
"  try{"
"    const r=await fetch('/api/status');"
"    if(!r.ok){$('sigSys').textContent='ERR';$('sigSys').className='bad';return;}"
"    const s=await r.json();"
"    $('sigSys').textContent='OK';$('sigSys').className='';"
"    $('sigHK').textContent=s.hk_paired?'PAIRED':'WAITING';"
"    $('sigHK').className=s.hk_paired?'':'bad';"
"    $('rPos').textContent=s.percent;"
"    $('rTgt').textContent=s.target_percent;"
"    $('rSteps').textContent=s.position+' / '+s.full_open;"
"    $('rState').textContent=s.moving?'MOVING':'STOPPED';"
"    $('rState').className='v state-'+(s.moving?'MOVING':'STOPPED');"
"    $('fill').style.width=s.percent+'%';"
"    $('tmark').style.left=s.target_percent+'%';"
"    if(!userDragging) $('slider').value=s.percent;"
"    lastTarget=s.target_percent;"
"  }catch(e){$('sigSys').textContent='LOST';$('sigSys').className='bad';}"
"}"

"function loadConfig(){"
"  fetch('/api/status').then(r=>r.json()).then(s=>{"
"    $('cfgPeriod').value=s.step_period_us;"
"    $('cfgHold').checked=s.hold_when_stopped;"
"    $('cfgFullOpen').value=s.full_open;"
"    $('cfgName').value=s.name||'';"
"    $('cfgCode').value=s.setup_code||'';"
"  });"
"}"

"function jog(n){if(n) api('/api/jog',{steps:n});}"
"function move(p){api('/api/move',{percent:p});}"
"function calibrate(a){"
"  if(confirm('Calibrate: '+a+'?\\nThis will overwrite the current calibration.'))"
"    api('/api/calibrate',{action:a}).then(refresh);"
"}"
"function saveConfig(){"
"  api('/api/config',{"
"    step_period_us:+$('cfgPeriod').value,"
"    hold_when_stopped:$('cfgHold').checked,"
"    full_open_steps:+$('cfgFullOpen').value,"
"    name:$('cfgName').value,"
"    setup_code:$('cfgCode').value"
"  }).then(()=>{const p=document.querySelector('[data-tag=CONFIG]');p.classList.add('flash');setTimeout(()=>p.classList.remove('flash'),400);refresh();});"
"}"
"function resetAll(){"
"  if(!confirm('FACTORY RESET will erase EVERYTHING.\\n\\nProceed?')) return;"
"  if(!confirm('Are you absolutely sure? Last chance.')) return;"
"  api('/api/reset',{});"
"}"
"function toggleAutoscroll(){autoscroll=!autoscroll;$('autoBtn').textContent='AUTOSCROLL: '+(autoscroll?'ON':'OFF');}"

"$('slider').addEventListener('input',e=>{userDragging=true;$('fill').style.width=e.target.value+'%';});"
"$('slider').addEventListener('change',e=>{userDragging=false;move(+e.target.value);});"

"function connectLog(){"
"  const ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws/logs');"
"  ws.onmessage=e=>{"
"    const log=$('log');"
"    const lvl=e.data.match(/\\b([EWIDV])\\s*\\(/);"
"    const cls=lvl?lvl[1]:'I';"
"    const div=document.createElement('div');"
"    div.className=cls;div.textContent=e.data;"
"    log.appendChild(div);"
"    while(log.children.length>500) log.removeChild(log.firstChild);"
"    if(autoscroll) log.scrollTop=log.scrollHeight;"
"  };"
"  ws.onclose=()=>setTimeout(connectLog,2000);"
"  ws.onerror=()=>ws.close();"
"}"

"refresh();loadConfig();connectLog();setInterval(refresh,1500);"
"</script>"
"</body></html>";
